### ISSUE TITLE
Implement edit suggestions based on simple spelling correction

### ISSUE THREAD

**Issue by fsteeg** [fsteeg/drc#20]

**Comment by claesn** [comment]
How to present (dropdown)?

**Comment by fsteeg** [comment]
Edit suggestions for selected word, closed by dffbd8673b081e6566d0c91c40ea3f3f7a8bc0af

**Comment by claesn** [comment]
Problems with edit suggestions:
- Windows: Always the same suggestion (word list seems to be interpreted as single string, line breaks?)
- should be possible to turn off suggestions, can lead to problems (e.g. when skipping through words too fast)
